# Generated by Django 2.2.5 on 2019-11-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_auto_20191015_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_author',
            field=models.ForeignKey(default=webapp.models.assign_author, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
