# Generated by Django 2.2.5 on 2019-11-04 14:15
import re

from django.db import migrations

from random_username.generate import generate_username
from transliterate import translit


def has_cyrillic(text):
    return bool(re.search('[\u0400-\u04FF]', text))

def create_authors(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Article = apps.get_model('webapp', 'Article')

    for article in Article.objects.all():
        author_name = ''.join(e for e in article.author if e.isalnum())
        if len(author_name) > 1: # - транслитерация не работает для строк длиной в один символ
            if has_cyrillic(author_name):
                    translit_author_name = translit(author_name, reversed=True)
                    user, created = User.objects.get_or_create(username=translit_author_name)
                    if created:
                        # user.set_password(translit_author_name.upper()) - миграция не может распознать функцию задать пароль от модели пользователя,
                        # в StackOverflow пишут, что это из-за наследования
                        user.save()
                        article.user_author = user
                        article.save()
                    else:
                        article.user_author = user
                        article.save()
            else:
                user, created = User.objects.get_or_create(username=author_name)
                if created:
                    # user.set_password(author_name.upper())
                    user.save()
                    article.user_author = user
                    article.save()
                else:
                    article.user_author = user
                    article.save()
        else:
            username = generate_username()[0]
            user = User.objects.create(username=username)
            # user.set_password(username.upper())
            user.save()
            article.user_author = user
            article.save()

def eliminate_authors(apps, schema_editor):
    Article = apps.get_model('webapp', 'Article')
    User = apps.get_model('auth', 'User')

    for article in Article.objects.all():
        article.author = article.user_author.username
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_user_author'),
    ]

    operations = [
        migrations.RunPython(create_authors, eliminate_authors)
    ]
